### ISSUE TITLE
Connection State has changed disconnected

### ISSUE THREAD

**Issue by hearsay316** [deepch/RTSPtoWebRTC#26] opened 2020-06-11 08:45 UTC
30s 
![image](https://user-images.githubusercontent.com/10139810/84364645-f0516680-ac02-11ea-9347-b09a972c73b0.png)

**Comment by kavyeshopenxcell** [comment] 2020-07-18 20:12
Duplicate of #22

**Comment by deepch** [comment] 2021-01-08 16:35
Try it in the new version there pion v3 was updated and rtsp v2 client was updated

**Closed** 2021-01-08 16:35 UTC
Labels: duplicate
